
version: 2
models: 

      - name: int_sales_margin
        description: purchase cost and gross margin by product and sale
        columns: 
          - name: products_id
            description: number that identify the product, per raw
          - name: date_date
            description: date of the sale
          - name: orders_id
            description: number that identify the the order
          - name: revenue
            description: total sale value of the product within the order.
          - name: quantity
            description: quantity of products sold
          - name: purchase_price
            description: Unit cost of the product to the company.
          - name: purchase_cost
            description: Cost of the entire quantity sold of that product in that sale
          - name: margin
            description: return per product

      - name: int_orders_margin
        description: margin per order
        columns: 
          - name: orders_id
            description: number that identify the the order
            tests:
              - not_null
              - unique
          - name: date_date
            description: date of the sale
          - name: revenue
            description: revenue of the order
          - name: quantity
            description: quantity of products sold per order
          - name: purchase_cost
            description: cost total for the company per order
          - name: margin
            description: return per each order        

      - name: int_orders_operational
        description: operational margin per order, including all the costs as purchases
        columns:
          - name: orders_id
            description: number that identify the order
            tests:
              - not_null
              - unique
          - name: date_date
            description: date that that order was made
          - name: operational_margin
            description: return without all the cost fot the company
          - name: revenue
            description: total amount received from each order
          - name: quantity
            description: quantaty of products sold per each order
            tests:
              - not_null
          - name: purchase_cost
            description: total amount of the expense per order
          - name: ship_cost
            description: costs to the company to organize the shipping per each order
          - name: shipping_fee
            description: total amount paid from the clients for shipping per each order
          - name: logCost
            description: cost of internal logistics (preparing, packaging, storing, processing) per order

      - name: finance_days
        description: Summarizes daily financial indicators, including revenue, operating margin, and transaction volume.
        columns:
          - name: date_date
            description: table organized per days
            tests:
              - not_null
              - unique
          - name: Total_transactions
            description: number os transactions per day
          - name: Total_revenue
            description: the total amount received from the sales per day
          - name: Average_Basket
            description: average amount in the basket per day
          - name: operational_margin
            description: financial return per day, already excluding all costs involved
          - name: purchase_cost
            description: total cost of all the products per day
          - name: Total_shipping_fees
            description: total amount paid about shipping taxes from the clients per day
          - name: Total_log_costs
            description: cost of internal logistics (preparing, packaging, storing, processing) per day
          - name: qty_products_sold
            description: how many products were sold per day