#define sources --> aqui identificamos onde estao os dados e podemos renomea-los para ser mais facil de os identificar ao longo do projeto
version: 2
sources:
  - name: raw                         # em vez de "wired-office-473608-g9" apenas "raw"
    database: wired-office-473608-g9  # project ID
    schema: gz_raw_data               # dataset on BigQuery
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship
