
version: 2
<<<<<<< HEAD
sources:
  - name: raw                         # em vez de "wired-office-473608-g9" apenas "raw"
    database: wired-office-473608-g9  # project ID
    schema: gz_raw_data               # dataset on BigQuery
    tables:
  ##__staging_models__##
        - name: sales
          identifier: raw_gz_sales
          description: sales of Greenweez / product_id per row associated to each orders_id
          loaded_at_field: date_date
          freshness:
            warn_after: {count: 90, period: day}   # avisa se a última linha tiver > 90 dias
          columns:
            - name: orders_products_id  # criei uma nova coluna com a concatenaçao de orders_id + products_id
              description: primary key of the table, agregation of orders_id with products_id
              tests:
                - unique
                - not_null
            - name: date_date
              description: date of purchase
            - name: orders_id
              description: identification of the orders
            - name: products_id
              description: identification of the ptoducts
            - name: revenue
              description: revenue associated to each ptoduct
            - name: quantity
              description: quantity of ptoducts per order_id
        - name: product
          identifier: raw_gz_product
          description: products of Greenweez / product_id per row associated to each purchase_price
          columns:
            - name: products_id
              description: a row per product_id
              tests:
                - unique
                - not_null
            - name: purchase_price
              description: price associated to each product_id
        - name: ship
          identifier: raw_gz_ship
          description: ships of Greenweez / orders_id per row associated to each ship_cost
          columns:
            - name: orders_id
              description: order_id per row
              tests:
                - unique
                - not_null
            - name: shipping_fee
              description: a shipping_fee associated to each order_id shipped
            - name: logCost
              description: log costs associated to each ship
            - name: ship_cost
              description: each ship cost, it's a fixed value (2.0)
    models: 
##__intermediate_models__##
#int_sales_margin#
      - name: int_sales_margin
        description: purchase cost and gross margin by product and sale
        columns: 
          - name: products_id
            description: number that identify the product, per raw
            tests:
              - not_null
          - name: date_date
            description: date of the sale
            tests:
              - not_null
          - name: orders_id
            description: number that identify the the order
            tests:
              - not_null
          - name: revenue
            description: total sale value of the product within the order.
            tests:
              - not_null
          - name: quantity
            description: quantity of products sold
            tests:
              - not_null
          - name: purchase_price
            description: Unit cost of the product to the company.
            tests:
              - not_null
          - name: purchase_cost
            description: Cost of the entire quantity sold of that product in that sale
            tests:
              - not_null
          - name: margin
            description: return per product
            tests:
              - not_null
#int_orders_margin#
      - name: int_orders_margin
        description:
        columns: 
          - name: orders_id
            description: number that identify the the order
            tests:
              - not_null
              - unique
          - name: date_date
            description: date of the sale
            tests:
              - not_null
          - name: revenue
            description: revenue of the order
            tests:
              - not_null
          - name: quantity
            description: quantity of products sold per order
            tests:
              - not_null
          - name: purchase_cost
            description: cost total for the company per order
            tests:
              - not_null
          - name: margin
            description: return per each order
            tests:
              - not_null              
#int_orders_operational#
      - name: int_orders_operational
        description: operational margin per order, including all the costs as purchases
        columns:
          - name: orders_id
            description: number that identify the order
            tests:
              - not_null
              - unique
          - name: date_date
            description: date that that order was made
            tests:
              - not_null
          - name: operational_margin
            description: return without all the cost fot the company
            tests:
              - not_null
          - name: revenue
            description: total amount received from each order
            tests:
              - not_null
          - name: quantity
            description: quantaty of products sold per each order
            tests:
              - not_null
          - name: purchase_cost
            description: total amount of the expense per order
            tests:
              - not_null
          - name: ship_cost
            description: costs to the company to organize the shipping per each order
            tests:
              - not_null
          - name: shipping_fee
            description: total amount paid from the clients for shipping per each order
            tests:
              - not_null
          - name: logCost
            description: cost of internal logistics (preparing, packaging, storing, processing) per order
            tests:
              - not_null
##__mart_models__##
#finance_days#
      - name: finance_days
        description: Summarizes daily financial indicators, including revenue, operating margin, and transaction volume.
        columns:
          - name: date_date
            description: table organized per days
            tests:
              - not_null
              - unique
          - name: Total_transactions
            description: number os transactions per day
            tests:
              - not_null
          - name: Total_revenue
            description: the total amount received from the sales per day
            tests:
              - not_null
          - name: Average_Basket
            description: average amount in the basket per day
            tests:
              - not_null
          - name: operational_margin
            description: financial return per day, already excluding all costs involved
            tests:
              - not_null
          - name: purchase_cost
            description: total cost of all the products per day
            tests:
              - not_null
          - name: Total_shipping_fees
            description: total amount paid about shipping taxes from the clients per day
            tests:
              - not_null
          - name: Total_log_costs
            description: cost of internal logistics (preparing, packaging, storing, processing) per day
            tests:
              - not_null
          - name: qty_products_sold
            description: how many products were sold per day
            tests:
              - not_null
=======
models: 

  - name: int_sales_margin
    description: purchase cost and gross margin by product and sale
    columns: 
      - name: products_id
        description: number that identify the product, per raw
        tests:
          - not_null
      - name: date_date
        description: date of the sale
        tests:
          - not_null
      - name: orders_id
        description: number that identify the the order
        tests:
          - not_null
      - name: revenue
        description: total sale value of the product within the order.
        tests:
          - not_null
      - name: quantity
        description: quantity of products sold
        tests:
          - not_null
      - name: purchase_price
        description: Unit cost of the product to the company.
        tests:
          - not_null
      - name: purchase_cost
        description: Cost of the entire quantity sold of that product in that sale
        tests:
          - not_null
      - name: margin
        description: return per product
        tests:
          - not_null

  - name: int_orders_margin
    description: margin per order
    columns: 
      - name: orders_id
        description: number that identify the the order
        tests:
          - not_null
          - unique
      - name: date_date
        description: date of the sale
        tests:
          - not_null
      - name: revenue
        description: revenue of the order
        tests:
          - not_null
      - name: quantity
        description: quantity of products sold per order
        tests:
          - not_null
      - name: purchase_cost
        description: cost total for the company per order
        tests:
          - not_null
      - name: margin
        description: return per each order
        tests:
          - not_null              

  - name: int_orders_operational
    description: operational margin per order, including all the costs as purchases
    columns:
      - name: orders_id
        description: number that identify the order
        tests:
          - not_null
          - unique
      - name: date_date
        description: date that that order was made
        tests:
          - not_null
      - name: operational_margin
        description: return without all the cost fot the company
        tests:
          - not_null
      - name: revenue
        description: total amount received from each order
        tests:
          - not_null
      - name: quantity
        description: quantaty of products sold per each order
        tests:
          - not_null
      - name: purchase_cost
        description: total amount of the expense per order
        tests:
          - not_null
      - name: ship_cost
        description: costs to the company to organize the shipping per each order
        tests:
          - not_null
      - name: shipping_fee
        description: total amount paid from the clients for shipping per each order
        tests:
          - not_null
      - name: logCost
        description: cost of internal logistics (preparing, packaging, storing, processing) per order
        tests:
          - not_null

  - name: finance_days
    description: Summarizes daily financial indicators, including revenue, operating margin, and transaction volume.
    columns:
      - name: date_date
        description: table organized per days
        tests:
          - not_null
          - unique
      - name: Total_transactions
        description: number os transactions per day
        tests:
          - not_null
      - name: Total_revenue
        description: the total amount received from the sales per day
        tests:
          - not_null
      - name: Average_Basket
        description: average amount in the basket per day
        tests:
          - not_null
      - name: operational_margin
        description: financial return per day, already excluding all costs involved
        tests:
          - not_null
      - name: purchase_cost
        description: total cost of all the products per day
        tests:
          - not_null
      - name: Total_shipping_fees
        description: total amount paid about shipping taxes from the clients per day
        tests:
          - not_null
      - name: Total_log_costs
        description: cost of internal logistics (preparing, packaging, storing, processing) per day
        tests:
          - not_null
      - name: qty_products_sold
        description: how many products were sold per day
        tests:
          - not_null
>>>>>>> bc2327ea4dbfa184c2e79c6c79cbb061bae9ed8d
